---
- name: Test the inventory script
  hosts: azure
  vars:
    #ansible_user: "{{ansible_env.f5_username}}"
    #ansible_ssh_pass: "{{ansible_env.f5_password}}"
#  connection: local
  gather_facts: yes
  tasks:
    - debug: msg="{{ inventory_hostname }} has powerstate {{ powerstate }}"
    - shell: "f5-rest-node /config/cloud/azure/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/scripts/failoverProvider.js"
