---
# vars file for f5-azure-scca
resource_group: "{{ansible_env.AZURE_RESOURCE_GROUP}}"
location:  "{{ansible_env.location}}"
jump_username: "{{ansible_env.f5_username}}"
jump_password: "{{ansible_env.f5_password}}"
