---
- name: Test the inventory script
  hosts: azure
  vars:
    f5_username: "{{ansible_env.f5_username}}"
    f5_password: "{{ansible_env.f5_password}}"
  connection: local
  gather_facts: yes
  tasks:
    - name: check license
      bigip_command:
       server: "{{ ansible_host }}"
       user: "{{f5_username}}"
       password: "{{f5_password}}"
       commands:
        - show /sys license
      register: license

#    - debug: msg="{{license.stdout}}"
#      when:
#       - '"active" in failover.stdout|first'

    - name: revoke license
      bigip_command:
       server: "{{ ansible_host }}"
       user: "{{f5_username}}"
       password: "{{f5_password}}"
       commands:
        - revoke /sys license
      when:
       - '"t load license, may not be operational" not in license.stdout|first'

#    - debug: msg="{{ inventory_hostname }} has powerstate {{ powerstate }}"
#    - shell: "f5-rest-node /config/cloud/azure/node_modules/f5-cloud-libs/node_modules/f5-cloud-libs-azure/scripts/failoverProvider.js"
