---
- hosts: localhost
  tasks:
  - name: Get External variables
    command: python grab_vars.py --action external_setup
    register: ext_vars
  # - name: debug output
  #   debug:
  #     msg: "{{ext_vars.stdout|from_json }}"
  - name: Setup External F5
    import_role:
      name: f5-azure-scca-external-setup
    vars:
      resource_group: "{{ansible_env.AZURE_RESOURCE_GROUP}}_F5_External"
      location:  "{{ansible_env.location}}"
      setup:
        "{{ext_vars.stdout|from_json }}"        

  - name: Get Internal variables
    command: python grab_vars.py --action internal_setup
    register: int_vars
  # - name: debug output
  #   debug:
  #     msg: "{{int_vars.stdout|from_json }}"
  - name: Setup Internal F5
    import_role:
      name: f5-azure-scca-internal-setup
    vars:
      resource_group: "{{ansible_env.AZURE_RESOURCE_GROUP}}_F5_Internal"
      location:  "{{ansible_env.location}}"
      setup:
        "{{int_vars.stdout|from_json }}"        

