---
# tasks file for f5-azure-scca-external
- name: Check if resource group exists
  azure_rm_resourcegroup_facts:
    name: "{{resource_group}}"
  register: output
- name: Debug External Parameters
  debug:
    msg: "{{parameters}}"
#  when: not output.ansible_facts.azure_resourcegroups
- name: Deploy External Environnment
  azure_rm_deployment:
    state: present
    location: "{{ location }}"
    resource_group_name: "{{resource_group}}"
    template: "{{ lookup('file','azuredeploy.json') }}"
    wait_for_deployment_completion: no

    parameters:
      "{{parameters}}"
  register: output
  when: not output.ansible_facts.azure_resourcegroups
- name: Add Routes
  bigip_static_route:
    destination: "{{item.destination}}"
    gateway_address: "{{item.gateway_address}}"
    name: "{{item.name}}"
    server: "{{item.server}}"
    user: "{{f5_username}}"
    password: "{{f5_password}}"
  with_items:
     - { name: 'mgmt',destination: '172.16.0.0/24', gateway_address: '192.168.1.1', server: '52.247.171.80', user: "{{f5_username}}", password: "{{f5_password}}" }