---
# tasks file for f5-azure-scca-external
- name: Check if resource group exists
  azure_rm_resourcegroup_facts:
    name: "{{resource_group}}"
  register: output
- name: Debug External Parameters
  debug:
    msg: "{{parameters}}"
#  when: not output.ansible_facts.azure_resourcegroups
- name: Deploy External Environnment
  azure_rm_deployment:
    state: present
    location: "{{ location }}"
    resource_group_name: "{{resource_group}}"
    template: "{{ lookup('file','azuredeploy.json') }}"
    wait_for_deployment_completion: no

    parameters:
      "{{parameters}}"
  register: output
  when: not output.ansible_facts.azure_resourcegroups
