---
# tasks file for f5-azure-scca
- name: Check if resource group exists
  azure_rm_resourcegroup_facts:
    name: "{{resource_group}}"
  register: output
- name: Deploy SCCA Environnment
  azure_rm_deployment:
    state: present
    location: "{{ location }}"
    resource_group_name: "{{resource_group}}"
    template: "{{ lookup('file','azuredeploy.json') }}"

    parameters:
      JumpBoxAdminUserName:
        value: "{{jump_username}}"
      JumpBoxAdminPassword:
        value: "{{jump_password}}"
  when: not output.ansible_facts.azure_resourcegroups
- name: Create a public ip address
  azure_rm_publicipaddress:
    resource_group: "{{resource_group}}"
    name: f5-alb-ext-pip0
    allocation_method: Static
# - name: Deploy ALB
#   azure_rm_loadbalancer:
#     name: f5-ext-alb
#     location: "{{ location }}"
#     resource_group: "{{resource_group}}"
#     probe_protocol: Http
#     probe_port: 80
#     probe_request_path: /
#     load_distribution: Default
#     idle_timeout: 4
#     public_ip_address: f5-alb-ext-pip0
